export default {
    // excel columns
    "name": '',
    "rownum": '№',
    "level": 'Livello',
    "id": 'Membro del club',
    "rawtitle": 'Rango',
    "unpayedOrders": 'P',
    "personalvolume": 'VP',
    "lgo": 'PVG',
    "nso": 'VRA',
    "maxzr": 'Max. 3R',
    "monthNoVolume": '#',
    "status": 'S',

    // title modifiers
    "shorthighest": "1",
    "longhighest": "prima volta",
    "shortopen": "a",
    "longopen": "aperto",
    "shortnew": "n",
    "longnew": "nuovo",

    // titles
    "shortConsumer": "C",
    "shortPremiumConsumer": "CV",
    "shortJuniorAssistant": "Aj",
    "shortAssistant": "A",
    "shortDirector": "D",
    "shortSilverDirector": "DA",
    "shortGoldenDirector": "DO",
    "shortEmeraldDirector": "DS",
    "shortDiamondDirector": "DB",
    "shortMaster": "M",
    "shortSilverMaster": "MA",
    "shortDoubleSilverMaster": "2MA",
    "shortGoldenMaster": "MO",
    "shortPlatinumMaster": "MP",
    
    "longConsumer": "Consumatore",
    "longPremiumConsumer": "Consumatore Premium",
    "longJuniorAssistant": "Assistente minore",
    "longAssistant": "Assistente",
    "longDirector": "Direttore",
    "longSilverDirector": "Direttore Argento",
    "longGoldenDirector": "Direttore d'oro",
    "longEmeraldDirector": "Direttore Smeraldo",
    "longDiamondDirector": "Direttore Diamante",
    "longMaster": "Maestro",
    "longSilverMaster": "Maestro d'argento",
    "longDoubleSilverMaster": "Maestro d'argento doppio",
    "longGoldenMaster": "Maestro d'Oro",
    "longPlatinumMaster": "Maestro di platino",

    // ui strings
    "selectFile": "Seleziona il file di rapporto",
    "directorsOnly": "Solo Direttori",
    "mastersOnly": "Solo maestri",
    "noOrdersXMonths": "Nessun acquisto fino a {0} mesi",
    "showFullStructure": "Mostra tutta la struttura",
    "parseFailedMessage": "Impossibile leggere il file. Controlla se la lingua del file è corretta. Se si verifica un errore, scrivimi a {0}"
};