export default {
    // excel columns
    "name": "",
    "rownum": "№",
    "level": "Уровень",
    "id": "Член клуба",
    "rawtitle": "Ранг/нД",
    "unpayedOrders": "P",
    "personalvolume": "ЛО",
    "lgo": "ЛГО",
    "nso": "НСО",
    "maxzr": "Max. 3Р",
    "monthNoVolume": "#",
    "status": "S",

    // title modifiers
    "shorthighest": "1",
    "longhighest": "впервые",
    "shortopen": "о",
    "longopen": "открытый",
    "shortnew": "н",
    "longnew": "новый",

    // titles
    "shortConsumer": "п",
    "shortPremiumConsumer": "пп",
    "shortJuniorAssistant": "мА",
    "shortAssistant": "А",
    "shortDirector": "Д",
    "shortSilverDirector": "СД",
    "shortGoldenDirector": "ЗД",
    "shortEmeraldDirector": "ИД",
    "shortDiamondDirector": "БД",
    "shortMaster": "М",
    "shortSilverMaster": "МС",
    "shortDoubleSilverMaster": "2МС",
    "shortGoldenMaster": "МЗ",
    "shortPlatinumMaster": "МП",
    
    "longConsumer": "Потребитель",
    "longPremiumConsumer": "Премиум потребитель",
    "longJuniorAssistant": "Младший Ассистент",
    "longAssistant": "Ассистент",
    "longDirector": "Директор",
    "longSilverDirector": "Серебрянный Директор",
    "longGoldenDirector": "Золотой Директор",
    "longEmeraldDirector": "Изумрудный Директор",
    "longDiamondDirector": "Бриллиантовый Директор",
    "longMaster": "Мастер",
    "longSilverMaster": "Серебрянный Мастер",
    "longDoubleSilverMaster": "Дабл Серебрянный Мастер",
    "longGoldenMaster": "Золотой Мастер",
    "longPlatinumMaster": "Платиновый Мастер",

    // ui strings
    "cardMonthNoOrder": "Без закупок: {0} мес",
    "selectFile": "Выбрать файл отчёта",
    "directorsOnly": "Только Директора",
    "groupUnderDirectors": "Группировать Потребителей под Директорами",
    "mastersOnly": "Только Мастера",
    "noOrdersXMonths": "Без закупок",
    "showFullStructure": "Показать всю структуру",
    "parseFailedMessage": "Не могу прочитать файл. Проверьте, правильно ли выбран язык файла. Если ошибка появляется, напишите мне, пожалуйста на {0}",
    
    "lblFrom": "от",
    "lblTo": "до",
    "months": "месяцев",

    "pointsPersonal": "баллов личного объёма",
    "pointsGroup": "баллов группового объёма",
    "pointsOverall": "баллов во всей структуре",
    "btnFilter": "Найти",
    "percentNextTitle": "% requirement for next title",

    "spinnerReadingFile": "Читаю файл...",
    "spinnerDrawing": "Прорисовываю..."
};